# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Liangzw\work\AutoBisect\AutoBisect.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(612, 668)
        MainWindow.setMinimumSize(QtCore.QSize(612, 668))
        MainWindow.setMaximumSize(QtCore.QSize(612, 668))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 10, 241, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 221, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbPerf = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbPerf.setFont(font)
        self.rbPerf.setObjectName(_fromUtf8("rbPerf"))
        self.horizontalLayout.addWidget(self.rbPerf)
        self.rbPower = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbPower.setFont(font)
        self.rbPower.setObjectName(_fromUtf8("rbPower"))
        self.horizontalLayout.addWidget(self.rbPower)
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 591, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 35, 571, 144))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.txtComcode = QtGui.QLineEdit(self.layoutWidget1)
        self.txtComcode.setText(_fromUtf8(""))
        self.txtComcode.setObjectName(_fromUtf8("txtComcode"))
        self.horizontalLayout_4.addWidget(self.txtComcode)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblCampaign = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCampaign.setFont(font)
        self.lblCampaign.setObjectName(_fromUtf8("lblCampaign"))
        self.horizontalLayout_6.addWidget(self.lblCampaign)
        self.txtCampaign = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.txtCampaign.setFont(font)
        self.txtCampaign.setText(_fromUtf8(""))
        self.txtCampaign.setObjectName(_fromUtf8("txtCampaign"))
        self.horizontalLayout_6.addWidget(self.txtCampaign)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblDevice = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblDevice.setFont(font)
        self.lblDevice.setObjectName(_fromUtf8("lblDevice"))
        self.horizontalLayout_7.addWidget(self.lblDevice)
        self.txtDevice = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.txtDevice.setFont(font)
        self.txtDevice.setObjectName(_fromUtf8("txtDevice"))
        self.horizontalLayout_7.addWidget(self.txtDevice)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lblBenchcfg = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBenchcfg.setFont(font)
        self.lblBenchcfg.setObjectName(_fromUtf8("lblBenchcfg"))
        self.horizontalLayout_8.addWidget(self.lblBenchcfg)
        self.txtBenchcfg = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        self.txtBenchcfg.setFont(font)
        self.txtBenchcfg.setObjectName(_fromUtf8("txtBenchcfg"))
        self.horizontalLayout_8.addWidget(self.txtBenchcfg)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.groupBox_4 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(180, 10, 161, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 131, 41))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.rbMBuild = QtGui.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbMBuild.setFont(font)
        self.rbMBuild.setCheckable(True)
        self.rbMBuild.setChecked(False)
        self.rbMBuild.setObjectName(_fromUtf8("rbMBuild"))
        self.horizontalLayout_9.addWidget(self.rbMBuild)
        self.rbLBuild = QtGui.QRadioButton(self.layoutWidget_2)
        self.rbLBuild.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbLBuild.setFont(font)
        self.rbLBuild.setObjectName(_fromUtf8("rbLBuild"))
        self.horizontalLayout_9.addWidget(self.rbLBuild)
        self.layoutWidget2 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(340, 620, 206, 31))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.startCode = QtGui.QLineEdit(self.layoutWidget2)
        self.startCode.setText(_fromUtf8(""))
        self.startCode.setObjectName(_fromUtf8("startCode"))
        self.horizontalLayout_2.addWidget(self.startCode)
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.startValue = QtGui.QLineEdit(self.layoutWidget2)
        self.startValue.setText(_fromUtf8(""))
        self.startValue.setObjectName(_fromUtf8("startValue"))
        self.horizontalLayout_2.addWidget(self.startValue)
        self.layoutWidget3 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 622, 206, 31))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.endCode = QtGui.QLineEdit(self.layoutWidget3)
        self.endCode.setText(_fromUtf8(""))
        self.endCode.setObjectName(_fromUtf8("endCode"))
        self.horizontalLayout_3.addWidget(self.endCode)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.endValue = QtGui.QLineEdit(self.layoutWidget3)
        self.endValue.setText(_fromUtf8(""))
        self.endValue.setObjectName(_fromUtf8("endValue"))
        self.horizontalLayout_3.addWidget(self.endValue)
        self.listCases = QtGui.QListWidget(self.centralWidget)
        self.listCases.setEnabled(False)
        self.listCases.setGeometry(QtCore.QRect(430, 630, 0, 0))
        self.listCases.setObjectName(_fromUtf8("listCases"))
        self.layoutWidget4 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 300, 571, 361))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        # self.label_5 = QtGui.QLabel(self.layoutWidget4)
        # self.label_5.setObjectName(_fromUtf8("label_5"))
        # self.horizontalLayout_10.addWidget(self.label_5)
        # self.txtStartBuild = QtGui.QLineEdit(self.layoutWidget4)
        # self.txtStartBuild.setObjectName(_fromUtf8("txtStartBuild"))
        # self.horizontalLayout_10.addWidget(self.txtStartBuild)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.btnShowRuned = QtGui.QPushButton(self.layoutWidget4)
        self.btnShowRuned.setObjectName(_fromUtf8("btnShowRuned"))
        self.horizontalLayout_10.addWidget(self.btnShowRuned)
        self.btnShowLog = QtGui.QPushButton(self.layoutWidget4)
        self.btnShowLog.setObjectName(_fromUtf8("btnShowLog"))
        self.horizontalLayout_10.addWidget(self.btnShowLog)
        self.btnShowHistory = QtGui.QPushButton(self.layoutWidget4)
        self.btnShowHistory.setObjectName(_fromUtf8("btnShowHistory"))
        self.horizontalLayout_10.addWidget(self.btnShowHistory)
        self.btnShowTask = QtGui.QPushButton(self.layoutWidget4)
        self.btnShowTask.setObjectName(_fromUtf8("btnShowTask"))
        self.horizontalLayout_10.addWidget(self.btnShowTask)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.listTask = QtGui.QListWidget(self.layoutWidget4)
        self.listTask.setObjectName(_fromUtf8("listTask"))
        self.verticalLayout_2.addWidget(self.listTask)
        self.listRunLog = QtGui.QListWidget(self.layoutWidget4)
        self.listRunLog.setObjectName(_fromUtf8("listRunLog"))
        self.verticalLayout_2.addWidget(self.listRunLog)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.btnDownload = QtGui.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DFKai-SB"))
        font.setPointSize(26)
        self.btnDownload.setFont(font)
        self.btnDownload.setObjectName(_fromUtf8("btnDownload"))
        self.horizontalLayout_11.addWidget(self.btnDownload)
        self.btnStart = QtGui.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DFKai-SB"))
        font.setPointSize(26)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.horizontalLayout_11.addWidget(self.btnStart)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 151, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 131, 41))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.rb3gr = QtGui.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rb3gr.setFont(font)
        self.rb3gr.setObjectName(_fromUtf8("rb3gr"))
        self.horizontalLayout_5.addWidget(self.rb3gr)
        self.rblte = QtGui.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rblte.setFont(font)
        self.rblte.setObjectName(_fromUtf8("rblte"))
        self.horizontalLayout_5.addWidget(self.rblte)
        self.layoutWidget.raise_()
        self.listCases.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Test", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Case Type", None))
        self.rbPerf.setText(_translate("MainWindow", "Performance", None))
        self.rbPower.setText(_translate("MainWindow", "Power", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Args", None))
        self.label_6.setText(_translate("MainWindow", "   COM Code", None))
        self.lblCampaign.setText(_translate("MainWindow", "    campaign", None))
        self.lblDevice.setText(_translate("MainWindow", "         device", None))
        self.lblBenchcfg.setText(_translate("MainWindow", "bench config", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Build Type", None))
        self.rbMBuild.setText(_translate("MainWindow", "M", None))
        self.rbLBuild.setText(_translate("MainWindow", "L", None))
        self.label.setText(_translate("MainWindow", "起始号", None))
        self.label_3.setText(_translate("MainWindow", "值", None))
        self.label_2.setText(_translate("MainWindow", "结束号", None))
        self.label_4.setText(_translate("MainWindow", "值", None))
        # self.label_5.setText(_translate("MainWindow", "Start Build", None))
        self.btnShowRuned.setText(_translate("MainWindow", "Runed Build", None))
        self.btnShowLog.setText(_translate("MainWindow", "Log", None))
        self.btnShowHistory.setText(_translate("MainWindow", "History", None))
        self.btnShowTask.setText(_translate("MainWindow", "Task", None))
        self.btnDownload.setText(_translate("MainWindow", "Start Download", None))
        self.btnStart.setText(_translate("MainWindow", "Start Run", None))
        self.groupBox.setTitle(_translate("MainWindow", "Device", None))
        self.rb3gr.setText(_translate("MainWindow", "3GR", None))
        self.rblte.setText(_translate("MainWindow", "LTE", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

